#pragma once

// Stubbed GeneratedBinding.hpp for mobile builds
// This file is normally auto-generated by Geode's build system.
// For Android/iOS builds where cocos/fmod are disabled, we provide
// empty definitions so the compiler is satisfied.

namespace geode {
    namespace generated {
        // Empty placeholder types and functions
        struct BindingInfo {
            const char* name;
        };

        inline void registerBindings() {
            // no-op
        }
    }
}